name: "Dev Branch Protection"
target: branch
enforcement: active

conditions:
  ref_name:
    exclude: []
    include:
      - "refs/heads/dev"

rules:
  - type: deletion

  - type: non_fast_forward

bypass_actors: []
