name: "Homolog Branch Protection"
target: branch
enforcement: active

conditions:
  ref_name:
    exclude: []
    include:
      - "refs/heads/homolog"

rules:
  - type: pull_request
    parameters:
      required_approving_review_count: 0
      dismiss_stale_reviews_on_push: true
      require_last_push_approval: false
      required_review_thread_resolution: false
      automatic_copilot_code_review_enabled: false
      allowed_merge_methods:
        - merge
        - squash
        - rebase

  - type: non_fast_forward

  - type: deletion

bypass_actors: []
